defaults: &defaults
  working_directory: /home/circleci/my-company-team-materialized-view
  docker:
    - image: circleci/openjdk:8-jdk-browsers
    
version: 2
jobs:
  build:
    <<: *defaults
    steps:

      - checkout

      - restore_cache:
          key: my-company-team-materialized-view-{{ checksum "pom.xml" }}

      - run: 
          name: Verify maven application (run any checks on results of integration tests to ensure quality criteria are met)
          command: mvn -s .circleci/maven.settings.xml verify -P idugalic-cloud

      - save_cache:
          paths:
            - ~/.m2
          key: my-company-team-materialized-view-{{ checksum "pom.xml" }}
      
      - run:
          name: Collecting test results
          command: |
            mkdir -p junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} junit/ \;
          when: always
          
      - store_test_results:
          path: junit/
          
      - store_artifacts:
          path: junit/

  deploy:
    <<: *defaults
    steps:

      - checkout

      - restore_cache:
          key: my-company-team-materialized-view-{{ checksum "pom.xml" }}
            
      - deploy:
          name: Deploy maven artifact
          command: mvn -s .circleci/maven.settings.xml -DskipTests deploy -P idugalic-cloud

      - save_cache:
          paths:
            - ~/.m2
          key: my-company-team-materialized-view-{{ checksum "pom.xml" }}
          
      - run:
          name: Collecting artifacts
          command: |
            mkdir -p artifacts/
            find . -type f -regex ".*/target/.*jar" -exec cp {} artifacts/ \;
     
      - store_artifacts:
          path: artifacts/

notify:
  webhooks:
    - url: https://webhook.atomist.com/atomist/circle
 
workflows:
  version: 2
  my-company-team-domain-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master